---
title: "Job mobility and earnings growth: diffrerent markets, different outcomes."
author: "Ivan"
date: "03 September 2018"
output: html_document
---

## Abstract:

**Purpose:** The article compares internal and external job mobility as a means of improving earnings growth in Germany and the UK.

**Design/methodology/approach:** We present parallel case studies using the British Household Panel Survey, and the German Socio-Economic Panel. Within both panels, we consider job history questions which operationalise voluntary internal and external job mobility. Using this data we estimate the effect of job mobility on earnings growth using fixed-effects estimation, and compare both countries. 

**Findings:** Internal and external mobility are distinctly different strategies for improving earnings. However, the institutional setting under which mobility takes place also shapes the rewards tied to mobility. In both countries the core workforce benefits from internal promotions. However, in Germany the rewards tied to promotion are far greater than they are in the UK. A key reason German workers are less mobile than British workers may have less to do with employment protection legislation and more to do with the rewards tied to internal career ladders.

**Practical implications:** Studies hoping to understand the link between job mobility and earnings growth must consider the importance of institutional frameworks. Labour market institutions shape not only the rate of job mobility in a given market, but also the rewards tied to mobility. 

**Originality/value:** Studies exploring the effects of job mobility tend to focus on single country cases. The lessons from such cases are then prescribed to other countries, without acknowledging that countries differ by capitalisms and institutional settings. Our paper articulates important differences in the mobility-earnings relationship between Germany and the UK, and helps to understand processes of inequality in both countries. German workers who are able to pursue internal promotion are likely different form those who are unable to pursue promotion. British workers also benefit from promotions, but must pursue several promotions before seeing a substantial difference in pay.



## Second abstract (different format)

Countries differ in their rates of job mobility and turnover. Researchers cite employment protection legislation as key to understanding the rates; however, the rewards or effects tied to mobility play a stronger role in determining differences. We consider this idea through two aims. First we compare the effects of quits and promotions on earnings growth. Second, we consider their effects in two institutional settings (Germany and the UK). Studies exploring the effects of job mobility are rare, studies which compare and contrast their effects in separate institutional frameworks, or capitalisms, are rarer. We offer two findings. First, quits and promotions have significantly different effects on earnings growth, depsite both commonly labeled as "voluntary". Internal promotions yield significant earnings growth for workers in both countries. Quits have a minor effect, which is explained by a change in weekly working hours. Second, the effect of promotions is larger in Germany than in the UK. This suggests the premium tied to promotion is greater in Germany than the UK. The high premium tied to internal mobility in Germany may act as an incentive to commit to the firm instead of the market, hence the lower rate of mobility among German workers. The article helps to understand country-differences in mobility rates; our explanations go beyond a nation's level of employment protection.  
 
## Introduction:

Worker mobility is a key strategy for improving outcomes like wages and conditions. Routinely, authors show that workers make significant gains through quitting or securing promotions. Despite this, capitalist countries differ in their rates of job mobility; especially in rates of voluntary mobility. Authors typically explain these differences as differences in the freedom to hire or fire workers (Brown) or a differences in the rate of job creation and destruction (OECD). This article argues that mobility rates also differ due to the rewards they offer to workers. More specifically, we propose that countries differ in the rewards tied to quits and promotions. 

The aim of the article is two-fold. First, we explicitly compare internal and external mobility as a means to improve eanings growth. Second, we compare this relationship under two different institutional settings, coordinated Germany and the liberal UK (Hall and Soskice, Thelen). Both aims stem from two wrinkles often found in the job mobility literature. The first is authors' tendency to ignore internal promotions as a form of voluntary mobility. Internal promotion are the main form of mobility desired by workers, yet authors often confine mobility types to external quits. Second, is the over-reliance on single case studies. Authors exploring the impact of mobility often use single country exmaples despite the fact that european labour markets are highly divided. Our article highlights this nuance by explicitly comparing quits and promotions in two different institutional settings. 

The theoretical literature has little to say on country differences in mobility rates, although certain hypotheses can be drawn out. In the *job-match* model, mobility stems from a mismatch between a worker's skills and her rewards or conditions (Jovanvich). In this way countries with low rates of job mobility, are simply countries with a good record of job matching. This would make sense in both Germany and the UK, where occupational licensing is prevalent in Germany, and less so in the UK. In the *job-search* model, mobility stems from the opportunity of higher wages. Thus if labour markets have a wide dispersion of wages, workers have more opportunity to match their reservation wages, which leads to more mobility. This too makes sense in the context of Germany and the UK. In gGermany wages inequality is far lower than in the UK, thus mobility between positions is less likely to lead to "wage-quits", when compared to the UK.  In *Human capital* theory, job mobility depends on the type of skills available to workers, either tranferable or firm specific. This approach may also apply to Germany and the UK, where German employers offer training in firm specific skills, while UK workers rely most on industry specific skills and tenure. 

We our approach is a parallel case study  which uses two longitudinal panels, the British Household Pnael Survey, and the German Socio-Economic Panel. It has three strengths. First, we include firm internal mobility into our analysis of mobility types. Second, take a longitudinal approach to estimating the effects of changing jobs. In this way, we avoid the conclusions of authors who compare movers to non-movers; instead we are able to observe the effects of moving from one position to another. Third, we compare and contrast the effects of moving in two different institutional settings, where authors typically rely on one.

We offer two findings. First, quits and promotions have significantly different effects on earnings growth, depsite both commonly labeled as "voluntary". Internal promotions yield higher pay for workers in both countries. Quits have a minor effect, which are largely explained by changes in working hours. Second, the effect of promotions is larger in Germany than in the UK. This suggests the premium tied to promotion is greater in Germany. This high premium may act as an incentive to commit to the firm instead of the market, hence the lower rate of mobility among German workers. The minor effect of internal promotion

The decline of career ladders and the “death” of careers (Cappelli, 1999) has prompted some to embrace flexible and mobile markets (Arthur and Rousseau, 2001, Tolbert, 1996). In the narrative, increased mobility is inevitable but workers are able to gain through quits what was on offer through promotion. Some argue the precarity and instability experienced by turbulent labour markets is good for workers overall, since efficient and successful businesses will pass earnings on to workers in the form of gains, like higher earnings and better conditions (Brown et al., 2008). Turbulent and mobile markets give workers choice and movement occurs through mobility to “better jobs”. Less often, the authors discuss the effects of involuntary mobility or immobility with a given employer. The aim of this paper is to consider the central claim that voluntary mobility rewards workers. The article first considers the effect of movement overall, then contrasts the effect by considering inter- and intra-firm mobility, and lastly contrasts the UK against Germany; two institutional contexts with separate capitalisms. 

## Micro-level theories on mobility

What are the micro-level theories on mobility and outcomes? 


## Mobility and earnings:

Almost every author exploring mobility and pay, comments on the lack of papers exploring the topic. However, a key group of articles contain nuanced results. Overall, articles agree that mobility has a positive effect on pay, which is not eliminated when controlling for educational or occupational categories; and so, movement to new positions, between and within firms, has a positive effect on earnings. From here, two groups of articles emerge, those claiming internal changes reward workers best (Gesthuizen and Dagevos, 2008, Le Grand and Tåhlin, 2002), in a way supporting the internal labour market theory of the efficiency wage theory, and those claiming that external changes reward workers best, supporting attainment theory (Pavlopoulos et al., 2007, Latzke et al., 2016). 

The articles considered here sample from a range of countries, but rarely contrast two countries against one another (the exception to this is Pavlopoulos et al. (2007) who compare both Germany and the UK). Keith and McWilliams (1999, 1995, 1997)  consider young US workers, and the effects of “employee initiated” changes. Elsewhere Kronberg (2013), considered the effect on inter-firm mobility in the US or earnings growth, finding a strong positive effect, especially for those in “god jobs”. Gesthuizen and Dagevos (2008) consider panel data from the Netherlands, and estimate the effect of both internal and external mobility types. Le Grand and Tåhlin (2002) estimate the short term and long term effects of mobility on pay using a Swedish sample. Latzke et al (2016), Schmelzer (2010), and Pavlopoulos et al. (2007) estimate the effect of external mobility in Germany. While Latzke et al. (2016) and Schmelzer (2010) ignore the effects of internal promotions, due to data concerns, Pavlopoulos et al. (2007) estimates the effect reporting no data related issues, and consider both Germany and the UK in their estimates.

In an extensive paper, Kronberg (2013) explores the effects of mobility on earnings growth in the US. Results reveal the effects of movement are positive but reliant on the quality of the job itself (good jobs versus bad). In the past (late 1970’s), respondents in “good” jobs (occupations with health insurance or pensions, where earning are above 120% of the federal poverty threshold) saw increased earnings after a voluntary change. This premium has grown over the years, suggesting workers see larger changes in pay following a change of employers. For workers in “bad jobs” voluntary mobility had no effect on earnings throughout the 70’s and 80’s. Those in poor occupations who quit jobs for new ones were able to recreate their pay with a new employer, but likely quit for better working conditions or hours, than for a type of career advancement or a change in pay. Over time a penalty began to emerge for workers who quit their jobs. This result runs completely counter to attainment theory as presented by Sørensen (1975), which claims that movement is driven by the opening of better vacancies alone, according to Kronberg (2013), the theory applies only to those working in the economic core. A major issue with the article is the fact that internal changes are not considered, although the paper is extensive in that it covers several groups and dynamics regarding the effects of mobility. This omission is problematic because the original issue at the heart of the papers, is the biased and discriminatory practice of internal labour markets, which is not tested. 

Remaining with the US, Keith and McWilliams estimate the effect of “employee initiated change”. Quitting an employer for economic reasons increased the earnings growth of workers, while quitting for family reasons lowered the earnings growth of workers. Some later evidence showed that prior search had a further positive effect on the earnings of workers (Keith and McWilliams, 1999). Schmelzer (2010) report a similar effect in Germany, where mobility to a new employer has a positive effect, especially if workers secure a new position before leaving a given employer (direct moves). Workers who quit without securing a new position, recreate their earnings, but see no increases in pay. 

Latzke et al. (2016) also find a positive effect between changing employers and increased pay. However, their findings differ somewhat when compared to Kronberg (2013). Latzke et al find that as mobility becomes more common, the returns tied to the change decline. Thus, in Germany the increased levels of mobility are correlated with a fall in the mobility premium. This could be the result of institutional differences, since Germany has industry level bargaining mechanisms tied to pay; as workers move they likely come closer to the industry norm, and hence the limit of their pay. Since the US is highly individualised, increased mobility may be fuelled by the increased pay which is tied to the move. 

The papers above outline the case for studying inter-firm changes, but do not consider the original method of career progress, internal or career ladder mobility. Here, articles differ somewhat between those supporting intra-firm changes (Gesthuizen and Dagevos, 2008, Le Grand and Tåhlin, 2002), and those supporting inter-firm mobility (Pavlopoulos et al., 2007). Comparing both Germany and the UK, Pavlopoulos et al. (2007) find that inter-firm mobility provides larger “gains” than intra-firm mobility through career ladders. Leaving an employer increases the earnings of low paid workers better than pursuing promotion. However, others are not positively affected by the change; inter-firm mobility has a negative effect on the earnings of high-paid workers. This is likely the result of workers moving for reasons other than pay. It’s possible that high-paid workers make inter-firm changes to make gains in bonuses, working conditions, or working time, none of which were considered by Pavlopoulos et al. (2007). Intra-firm mobility has a positive effect on low paid workers in the UK alone. German workers who take promotions with the same employer see no significant change in wages, suggesting the effect is explained by the other variables in the model, possibly occupation. This is a surprising finding, since German labour markets contain lower rates of mobility, and are typically more coordinated, resulting in longer rates of tenure with the same employer. Pavlopoulos et al. (2007) claim this makes sense, British workers are vulnerable to poaching, and as a result, employers must offer efficiency wages in order to prevent workers from leaving. 

## Macro-level theories on mobility
    
## Institutional differences

### Data and sample:

The sample is drawn from the British Household Panel Survey, and the German Socio-Economic Panel, both are representative of British and German workers. Respondents in both panels are questioned annually, and the period studied covers 2000-2008. This period crosses both panels, and stops sampling workers before the European Debt Crisis. Since the crisis had significant negative effects in both countries, it is not representative of either labour market, and so is ommitted. Each panel contains socio-economic variables, detailed job history files, household composition details, employment details and several satisfaction measures. 

Both samples are defined as follows, respondents with at least 8 observations between 2000 and 2008; respondents employed at each interview; respondents not in self employment, unemployment or inactivity; respondents without missing values for questions related to job mobility. Each available region is considered in both countries; for the UK this is England, Scotland, Wales and Northern Ireland, for Germany this is both East and West. The final shape takes the form of a person-year file which ignores household composition in favour of individual responses. Due to this definition, the models rely on a semi-balanced panel of the core workforce, who remain employed throughout. Respondents who fall in and out of unemployment are not considered which may be more problematic for Germany than the UK, where spells of unemployment tend to last longer. 

The UK data draws from year-specific individual-response files “INDRESP”, and individual job history files “JOBHIST” which contain person-specific job-spell information for the given year. This dataset is used to construct the mobility variables proposed below. The German data draws from the SOEP-Long file, a longitudinal version of the individual response files. The resulting UK sample is made up of 3,782 respondents with 32,560 person-year observations. The German sample is made up of 4,444 individuals and 36,687 person-year observations. Both are summarised in Table 1. 

 [table 1 here]
 
 The outcome used throughout the article is gross monthly wages. The measure features in the SOEP-Long file (plc0013) and the BHPS’s individual response file (paygu). Gross earnings are preferred since both countries differ in terms of income tax. Further, since both countries differ by currencies, both sets of values are converted to US dollars ($) as valued in January 2008. In the UK, 1 British pound was worth 0.507 dollars. In Germany 1 euro was worth 0.680 dollars. Further, since wages are not normally distributed, each model considers the natural log of these wages.
 
Mobility is defined using three variables. In the UK, movement and non-movement are defined by changes in spell (jspno), comparing respondents with a change (movement) against those without a change (non-movement). In Germany, basic mobility is captured using the survey question “new job since last year?” (plb0031). Observations containing movement are separated by inter-firm and intra-firm movement. This is captured using the variable asking the location of the change, in the UK the variable “JHSTAT” is used, in Germany the variable “plb0284” is used. Whether the change occurs voluntarily or involuntarily is defined subjectively using the available categories. The variable “JHSTPY” is used in the UK. The variable “plb0304” is used in Germany. Observations listing promotions, better jobs, and own resignations are assumed voluntary. Those listing redundancies, firm closures and dismissals are assumed involuntary. Those leaving for reasons tied to childcare or retirement are isolated in the “other” category. As an aside, the SOEP-long file cannot distinguish between voluntary and involuntary changes within the firm, for this reason, all intra-firm changes are estimated together, similar to Pavlopoulos et al. (2007). Combining all categories will likely underestimate the effect of promotions, since the category contains all changes, promotions, demotions, and lateral changes.  

Several controls are drawn from the individual response file and the Cross National Equivalence Files in both panels. Age, the number of children in the house, contract type, size of firm and industry and occupation of the worker are used. Lastly, models control for the survey wave, the country level of unemployment in a given year and the rate of economic growth in a given year. The macro indicators were dropped when estimating the effect for Germany due to issues of colinearity. Unemployment, growth, and year dummies, do not vary significantly, and correlate strongly. 

## Estimation:

Job mobility is not a random event, and so the effects are estimated using fixed-effects linear regression (Allison, 2009, Longhi and Nandi, 2014, Rabe-Hesketh and Skrondal, 2008). Individual heterogeneity will affect mobility estimates, since those who pursues quits or promotions will also have person-specific differences to the average worker (motivated or otherwise employable). By ignoring individual heterogeneity, the estimates for promotion say, would be inflated by person specific error terms, which artificially increase the effect of a promotion on outcomes (Longhi and Nandi, 2014). Further, since repeated observations are used, standard errors are clustered by respondents’ ID numbers. Longitudinal weights are provided in both panels, but those in the BHPS greatly reduce the number of observations available. Since weighted and non-weighted estimates do not differ significantly, clustered standard errors are used in both countries to correct for repeat observations. 

Previous authors use a similar method, Gesthuizen and Dagevos (2008) estimate the effect of inter and intra-firm mobility using a difference in difference approach, similar to a within-estimator, for several waves of data. Latzke et al. (2016) use propensity score matching to avoid the issue using German data. Pavlopoulos et al. (2007) also use fixed-effects regression when estimating the effect. Fixed-effects estimation controls for unobserved heterogeneity by transforming a typical Ordinary Least Squares regression model to a “within-transformation” linear model (Longhi and Nandi, 2014). This produces person-specific estimates of job mobility, which are unbiased by person-specific errors. The method is particularly suited to Sørensen (1977) who argues  worker resources are fixed from the moment they enter the labour market. Thus the estimate of mobility is the effect of “closing the gap” between resources and reward (attainment). 

All outcomes are linear, hence linear models with fixed-effects are considered (Allison, 2009, Rabe-Hesketh and Skrondal, 2008). Stata’s  xtreg,fe function is used throughout. One limitation should be mentioned, fixed-effects linear models rely only on within-respondent variation for estimation. Between-respondent variation is ignored or cancelled out, limiting the amount of data available. As a result, standard errors are larger than in random-effects models and sensitive to categories with few observations, this may be especially important for Germany, which has fewer mobility events than the UK. For this reason, estimates with p-values less than 0.1 are considered significant throughout.

## Results:

The estimates are listed in the table below. German models rely on 30,000+ observations from 4,000+ respondents, while the British estimates rely on 26,000+ observations from 3,500+ respondents. In each model, the R-squared figure is consistently higher in Germany than the UK, despite using identical controls. This also makes sense due to the higher levels of pay inequality in Germany when compared to the UK.  

[table 2]

Considering models 1 and 2, both countries differ at the baseline. British workers earn less (6.65) than their German counterparts (7.28) when all controls are at zero. Further, the standard errors reveal that the British baseline is less predictable (0.25) than the German one (0.17). These estimates make sense; income inequality is far higher in the UK than Germany. The German 90/10 ratio of income inequality is 3.25 (2000-2002), while the same measure for the UK is 4.67 (Ó Riain, 2014). Thus Germany’s top ten percent earned three times more than its bottom ten percent, and the UK’s top ten percent earned four times more than its bottom ten percent. 

Voluntary mobility has a positive but minor effect in both countries. Generally, respondents who move voluntarily experience a significant increase in pay. Respondents in the UK see a 2% increase in earnings after an inter-firm and intra-firm change. German respondents reveal more complicated results, here inter-firm mobility lowers the wages of workers (2%), and intra-firm mobility increases the earnings of workers (5%).  This is a counter intuitive finding that goes against attainment theory, since mobility is mostly driven by utilitarian gain, the most common predictor of which is earnings. Overall voluntary mobility has a positive effect in models 1 and 2. 

Regarding nuance, British workers improve their pay through mobility roughly equally, whether the change is inter-firm or intra-firm. Thus whether workers quit to a new employer, or take a promotion with an existing employer, they see an increased rate of pay of 2%. In Germany, the negative effect is tied to inter-firm mobility, but the positive effect is tied to intra-firm mobility. Thus leaving an employer behind for a new one results is lower earnings, but taking a promotion in an existing career ladder has a large significant effect of earnings. 

Controlling for weekly working hours (models 3 and 4) simplifies the estimates, now voluntary inter-firm change is insignificant, but intra-firm change is positive in both countries. Once weekly working hours are considered the inter-firm effect in both countries disappears, suggesting workers who change employers primarily work different hours. In Germany, workers work lower weekly hours after leaving an employer, suggesting they trade weekly working hours for more interesting or satisfying forms of work. In the UK, movers appear to work longer hours for the same rate of pay after leaving an employer, suggesting they make gains in hours, not pay. What remains after controlling for weekly working hours is a statistically significant estimate for intra-firm mobility or promotions in both countries. The finding is interesting because it remains significant in both countries despite the institutional differences which promote mobility in the UK and deter mobility in Germany. In both contexts, promotion raises pay without increasing working hours. The effect is larger in Germany than it is in the UK, suggesting British workers may have to pursue several promotions before seeing a substantial change in pay, while German workers see larger gains from possibly fewer “instances” of promotion. 

The findings above run counter to those of several authors. First, results find no positive effect for inter-firm mobility in either country. A positive link between changing employers and increasing earnings is often reported. In Germany, Latzke et al. (2016), Schmelzer (2010) and Pavlopoulos et al. (2007) report as much using SOEP data. Each finds a positive link between inter-firm mobility and pay, and controls for working hours. It’s possible the economic core does not benefit from the changes as much as those at the periphery, who may be reliant on the strategy. The findings reported here are similar to Gesthuizen and Dagevos (2008), where inter-firm mobility brought only a 1% increase in pay after the move. Second, intra-firm mobility is particularly significant in both countries. Most authors do not consider the effect of intra-firm change, comparing only between-firm mobility, to respondents who stay with the same employer. In this way it’s not clear if the reference category in these studies contains internal movers. 

